Make AssetScale optional
XRPLF/XRPL-Standards pull request #127
Opened 2023-08-15 21:07 UTC by sappenin

Per this [PR comment](https://github.com/ledhed2222/rippled/pull/1/files#r1255074771), this change makes `AssetScale` optionally supplied in `CFTokenIssuanceCreate` transactions.

2023-08-16 00:19 UTC, intelliot approved these changes
I think this is fine, but why is it called `AssetScale`? Does it have the same purpose/meaning as [ERC-20](https://eips.ethereum.org/EIPS/eip-20)'s `decimals`? If so, I would prefer to call it `Decimals` for better ease of understanding.

2023-08-16 16:29 UTC, sappenin commented
> I think this is fine, but why is it called `AssetScale`? Does it have the same purpose/meaning as [ERC-20](https://eips.ethereum.org/EIPS/eip-20)'s `decimals`? 

Yes, I think the two meanings are the same. What do you think about also using `Symbol` instead of `AssetCode`?

2023-08-16 17:59 UTC, intelliot commented
> Yes, I think the two meanings are the same. What do you think about also using `Symbol` instead of `AssetCode`?

Sounds good to me!

2023-08-16 19:11 UTC, sappenin commented
> https://github.com/XRPLF/XRPL-Standards/pull/127#issuecomment-1680921275

@ledhed2222 @nkramer44 @seelabs Any opinion on this terminology change?

2023-08-17 15:37 UTC, ledhed2222 commented on XLS-0033d-CFTs/README.md
> +## 1.1. Abstract
errant space

2023-08-17 15:37 UTC, ledhed2222 approved these changes

2023-08-17 15:51 UTC, ledhed2222 commented
actually - i've incorporated this into my other PR https://github.com/XRPLF/XRPL-Standards/pull/123

since that hasn't been reviewed yet, let's make it a place for ongoing changes rather than having multiple open PRs in this repo

2023-08-17 15:51 UTC, ledhed2222 requested changes
see note - please close :)

2023-08-17 21:16 UTC, sappenin commented
> actually - i've incorporated this into my other PR https://github.com/XRPLF/XRPL-Standards/pull/123 Since that hasn't been reviewed yet, let's make it a place for ongoing changes rather than having multiple open PRs in this repo

Sounds great, closing this PR in favor of https://github.com/XRPLF/XRPL-Standards/pull/123

2023-08-17 22:45 UTC, sappenin commented
@ledhed2222 - given that there's a lot of discussion in your [new CFT spec PR](https://github.com/XRPLF/XRPL-Standards/pull/123), how do you feel about me re-opening this one so we don't have a bunch of open issues being debated in one place (i.e., your other PR)?

(Trying to reduce as much noise as possible).

2023-10-25 22:12 UTC, sappenin commented
Closing this PR in-favor of https://github.com/XRPLF/XRPL-Standards/pull/137, which has everything in this PR.

2023-10-25 22:12 UTC, closed without merging