XLS-0046d-dynamic-non-fungible-tokens/README.md
XRPLF/XRPL-Standards pull request #205
Opened 2024-07-03 16:15 UTC by xVet

XLS-46d dNFTs - Spec PR

Implementation PR: https://github.com/XRPLF/rippled/pull/5048

Discussion: https://github.com/XRPLF/XRPL-Standards/discussions/130

2024-07-03 17:21 UTC, xVet commented
@tequdev lmk if the spec is now final so we can review/merge request,  thx :) !

2024-07-04 00:15 UTC, tequdev requested changes

2024-07-04 00:15 UTC, tequdev commented on XLS-0046d-dynamic-non-fungible-tokens/README.md
> +| `lsfMutable` | `0x00000016` | `Allow issuer (or an entity authorized by the issuer) to modify “URI”.` |
```suggestion
### 3.1 tfMutable

New flags for `NFTokenMint`:


| Flag Name	        | Flag Value       |  Description     | 
|-------------------|:----------------:|:-------------------------------------------------------------------------------------:|
| `tfMutable` | `0x00000010` | `Allow issuer (or an entity authorized by the issuer) to modify “URI”.` |
```

2024-07-04 00:15 UTC, tequdev commented on XLS-0046d-dynamic-non-fungible-tokens/README.md
> +	  }
```suggestion
	{
	  "TransactionType": "NFTokenModify",
	  "Account": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
	  "Owner": "rogue5HnPRSszD9CWGSUz8UGHMVwSSKF6",
	  "Fee": "10",
	  "Sequence": 33,
	  “NFTokenID”: “0008C350C182B4F213B82CCFA4C6F59AD76F0AFCFBDF04D5A048C0A300000007",
	  "URI": "697066733A2F2F62616679626569636D6E73347A736F6C686C6976346C746D6E356B697062776373637134616C70736D6C6179696970666B73746B736D3472746B652F5665742E706E67",
	
	  ...
	
	  }
```

Added a required field "Account" and changed the URI field to a hex string.

2024-07-04 00:15 UTC, tequdev commented on XLS-0046d-dynamic-non-fungible-tokens/README.md
> +If `lsfMutable` is set, executing NFTokenModify should fail when neither `Issuer` or an `account`authorized via `NFTokenMinter`, according to the specific flag, is executing the transaction.
```suggestion
If `tfMutable` is not set, executing NFTokenModify should fail!

If `tfMutable` is set, executing NFTokenModify should fail when neither `Issuer` or an `account` authorized via `NFTokenMinter`, according to the specific flag, is executing the transaction.
```

2024-07-04 00:15 UTC, tequdev commented on XLS-0046d-dynamic-non-fungible-tokens/README.md
> +		- lsfMutable
```suggestion
		- tfMutable
```

2024-07-04 14:04 UTC, xVet commented
@tequdev thanks a lot for the review, all suggestions included !

2024-07-05 14:45 UTC, mvadari commented on XLS-0046d-dynamic-non-fungible-tokens/README.md
> +XLS-20 provides -Non-Fungible Token- support, these tokens are immutable and don’t allow any changes. Currently NFTs can’t be modified, resulting often in new mints, which leads to ledger bloat that
```suggestion
[XLS-20](link to spec) provides [Non-Fungible Token](link to docs) support, these tokens are immutable and don’t allow any changes. Currently NFTs can’t be modified, resulting often in new mints, which leads to ledger bloat that eat valuable resources as well as experimental approaches to use website endpoints to mimic dynamic abilities.
```

2024-08-24 19:20 UTC, xVet commented
XLS-46D Spec is now closed and can be found here: https://github.com/XRPLF/XRPL-Standards/discussions/130

2025-01-01 12:41 UTC, FleetHub1988 reviewed
merge review

2025-05-14 12:53 UTC, mvadari commented
@xVet is this good to go?

2025-05-16 16:04 UTC, merged